version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: benchmark_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: benchmark_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always

  postgres:
    image: postgres:latest
    container_name: benchmark_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: benchmark_db
    ports:
      - "5432:5432"
    restart: always
